spring:
  application:
    name: gateway
  profiles:
    include: route
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        watch:
          enabled: true

server:
  port: 8000